import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#24292e', 
    },
    title: {
        fontSize: 50,
        fontWeight: 'bold',
        textAlign: 'center',
        marginVertical: 20,
        color: '#ffffff', 
        fontStyle: 'italic',
        fontVariant: ['small-caps'],
    },
    card: {
        marginTop: 50,
        width: '100%',
        alignSelf: 'center',
        padding: 15,
        borderRadius: 25,
        backgroundColor: '#1b2838', 
        marginVertical: 10,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.3,
        shadowRadius: 2,
        elevation: 2,
    },
    item: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        margin:5,
        padding: 15,
        fontSize: 18,
    
        backgroundColor: '#1b2838', 
        borderRadius: 5,
        marginVertical: 5,
      
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.3,
        shadowRadius: 2,
        elevation: 2,
    },
    input: {
        marginBottom: 10,
        backgroundColor: 'white',
        paddingHorizontal: 10,
        height: 50,
        borderRadius: 5,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.3,
        shadowRadius: 2,
        elevation: 2,
    },
    badd: {
        alignSelf: 'center',
        margin: 10,
        width: 40, 
        height: 50, 
        borderRadius: 25, 
        justifyContent: 'center', 
        backgroundColor: 'rgba(10, 10, 10, 0.8)', 
    },
 
    bdelete: {
        backgroundColor: '#FF3B30', 
        padding: 10,
        borderRadius: 10,
        fontWeight: 'bold',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.25,
        shadowRadius: 10,
        elevation: 5,
    },
    bfont: {
        color: '#ffffff',
        fontWeight: 'bold',
        fontSize: 16,
    },
    error: {
        color: 'red',
        marginLeft: 10,
        marginBottom: 10,
        fontWeight: 'bold',
      },
    nameContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    name: {
        fontSize: 23,
        fontWeight: '600',
        color: '#ffffff', 
        marginLeft: 15,
    },
    quantity: {
        fontSize: 16,
        color: 'white',
        backgroundColor: 'rgba(10, 10, 10, 0.8)', 
        width: 30, 
        height: 30, 
        borderRadius: 15, 
        textAlign: 'center', 
        lineHeight: 30, 
        textAlignVertical: 'center', 
    },
});